apiVersion: v1
kind: Service
metadata:
  name: {{ include "postgres-k8s-nlb.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "postgres-k8s-nlb.labels" . | nindent 4 }}
  {{- if .Values.service.enablePrivateLink }}
  annotations:
    # AWS Load Balancer Controller annotations for NLB creation
    {{- range $key, $value := .Values.service.nlbAnnotations }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
    
    # Deterministic tags for Terraform discovery
    service.beta.kubernetes.io/aws-load-balancer-additional-resource-tags: >-
      omnistrate-instance={{ .Release.Namespace }},
      omnistrate-service=postgres-nlb,
      service.k8s.aws/stack={{ .Release.Namespace }}/postgres-nlb,
      elbv2.k8s.aws/cluster={{ .Values.global.kubernetesClusterID | default "omnistrate-cluster" }}
  {{- end }}
spec:
  type: {{ if .Values.service.enablePrivateLink }}LoadBalancer{{ else }}ClusterIP{{ end }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 5432
      protocol: TCP
      name: postgres
  selector:
    {{- include "postgres-k8s-nlb.selectorLabels" . | nindent 4 }}

---
{{- if .Values.service.enablePrivateLink }}
# Additional service for internal cluster access (ClusterIP)
apiVersion: v1
kind: Service
metadata:
  name: {{ include "postgres-k8s-nlb.fullname" . }}-internal
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "postgres-k8s-nlb.labels" . | nindent 4 }}
    service-type: internal
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 5432
      protocol: TCP
      name: postgres
  selector:
    {{- include "postgres-k8s-nlb.selectorLabels" . | nindent 4 }}
{{- end }}
